#!/bin/bash
read -p "Do you want rm $2 ?" -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
	rm -rf $2
fi

read -p "Do you want rm $1 ?" -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
	rm -rf $1
	echo "sleep 5;rm -rf $1" > /tmp/gitSyncRm
	chmod 777 /tmp/gitSyncRm
	nohup /tmp/gitSyncRm &
fi

